---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: cf-pipeline
- name: runtime-configs

outputs:
- name: build

params:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:

run:
  path: cf-pipeline/tasks/bosh-apply-runtime-configs/bosh-apply-runtime-configs.sh