---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: cf-pipeline
- name: cf-deployment-release
- name: deployment-profiles

outputs:
- name: build

params:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  DEPLOYMENT_NAME:
  DEPLOYMENT_FILE:
  DEPLOYMENT_PROFILE:

run:
  path: cf-pipeline/tasks/bosh-deploy/bosh-deploy.sh